artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/sanaamin9940/Text-Summarization-NLP-project/raw/main/samsum%20data.zip
  source_URL_file_name: samsum data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
